language: java
jdk:
- openjdk8

install: true

script: mvn install

before_install:
- mvn clean


branches:
  only:
  - master

#after_success:
#  - mvn clean cobertura:cobertura coveralls:report

notifications:
  slack: cheese-dev:JXKSTVY4wHsMPbJi2uoKtyxs