language: java
jdk:
- openjdk8

before_install:
- mvn clean
- mysql -e 'CREATE DATABASE IF NOT EXISTS service;'

install: true

script: mvn install

branches:
  only:
  - master

after_success:
- mvn clean cobertura:cobertura coveralls:report

notifications:
  slack: cheese-dev:JXKSTVY4wHsMPbJi2uoKtyxs