spring:
  profiles:
    active: local


# Local
---
spring:
  profiles: local
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    ROOT: info
    org:
      hibernate:
        type: trace
